import { defineComponent, h } from 'vue'
import type { IconAliases, IconProps, IconSet } from 'vuetify'

import {
  ArrowCircleLeftBoldIcon,
  ArrowCircleRightBoldIcon,
  ArrowLeftBoldIcon,
  ArrowRightBoldIcon,
  ArrowSquareOutBoldIcon,
  ArrowUpRightBoldIcon,
  CaretCircleDownBoldIcon,
  CaretCircleLeftBoldIcon,
  CaretCircleRightBoldIcon,
  CaretCircleUpBoldIcon,
  CaretDoubleDownBoldIcon,
  CaretDoubleLeftBoldIcon,
  CaretDoubleRightBoldIcon,
  CaretDoubleUpBoldIcon,
  CaretDownBoldIcon,
  CaretLeftBoldIcon,
  CaretRightBoldIcon,
  CaretUpBoldIcon,
  ChatCircleBoldIcon,
  CheckBoldIcon,
  LinkBoldIcon,
  MinusBoldIcon,
  MinusSquareBoldIcon,
  PencilSimpleLineBoldIcon,
  PlusBoldIcon,
  PlusSquareBoldIcon,
  SpinnerGapBoldIcon,
  UserBoldIcon,
  WarningBoldIcon,
  WarningCircleBoldIcon,
  WarningDiamondBoldIcon,
  XBoldIcon,
} from '@/assets/icons/bold'
import {
  BookmarkFilledIcon,
  CalendarDotsFilledIcon,
  CaretDownFilledIcon,
  CaretLeftFilledIcon,
  CaretRightFilledIcon,
  CaretUpFilledIcon,
  ChatCircleFilledIcon,
  ChatTeardropFilledIcon,
  CheckCircleFilledIcon,
  CircleFilledIcon,
  DatabaseFilledIcon,
  DotActive,
  DotInactive,
  EnvelopeFilledIcon,
  HouseFilledIcon,
  InfoFilledIcon,
  MagnifyingGlassFilledIcon,
  MapPinFilledIcon,
  PencilLineFilledIcon,
  PlayFilledIcon,
  QuestionFilledIcon,
  StarFilledIcon,
  TrashFilledIcon,
  UserCircleFilledIcon,
  WarningCircleFilledIcon,
  WarningDiamondFilledIcon,
  WarningFilledIcon,
  XCircleFilledIcon,
} from '@/assets/icons/filled'
import CheckboxOffIcon from '@/assets/icons/inputs/CheckboxOffIcon.vue'
import CheckboxOnIcon from '@/assets/icons/inputs/CheckboxOnIcon.vue'
import RadioOffIcon from '@/assets/icons/inputs/RadioOffIcon.vue'
import RadioOnIcon from '@/assets/icons/inputs/RadioOnIcon.vue'
import {
  BriefcaseLightIcon,
  CoinsLightIcon,
  HandCoinsLightIcon,
  HeartbeatLightIcon,
  MoneyLightIcon,
} from '@/assets/icons/light'
import {
  ArrowBendUpLeftIcon,
  ArrowBendUpRightIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOut,
  ArrowSquareRight,
  ArrowUpIcon,
  ArrowUpRight,
  ArrowsClockwiseIcon,
  ArrowsOutCardinalIcon,
  BookBookmarkIcon,
  BookOpenTextIcon,
  BookmarkIcon,
  BooksIcon,
  BriefcaseIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CameraIcon,
  CaretCircleLeftIcon,
  CaretCircleRightIcon,
  CaretCircleUpIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChatCircleDotsIcon,
  ChatIcon,
  ChatTeardropIcon,
  ChatTextIcon,
  ChatsIcon,
  CheckCircleIcon,
  CheckIcon,
  CheckSuccessIcon,
  CircleIcon,
  ClipboardIcon,
  ClockIcon,
  CloseIcon,
  CopyIcon,
  CreditCardIcon,
  CropIcon,
  DatabaseIcon,
  DeviceMobileCameraIcon,
  DeviceTabletIcon,
  DotsThreeIcon,
  DownloadIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EtaIcon,
  EyeClosedIcon,
  EyeIcon,
  EyeSlashIcon,
  FileArrowDownIcon,
  FileArrowUpIcon,
  FileCodeIcon,
  FileCsvIcon,
  FileDocIcon,
  FileIcon,
  FileMagnifyingGlassIcon,
  FilePdfIcon,
  FilePlusIcon,
  FileTextIcon,
  FlagIcon,
  FolderArrowDownIcon,
  FolderArrowUpIcon,
  FolderIcon,
  FolderLockIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FunnelIcon,
  FunnelSimpleIcon,
  FunnelSimpleXIcon,
  FunnelXIcon,
  GearIcon,
  GlobeIcon,
  HandIcon,
  HandPointingIcon,
  HandShakeIcon,
  HandWavingIcon,
  HandsClappingIcon,
  HeadphonesIcon,
  HeartIcon,
  HouseIcon,
  HouseLineIcon,
  IdentificationCardIcon,
  InfoIcon,
  KeyIcon,
  LightbulbIcon,
  LinkIcon,
  ListBulletsIcon,
  ListChecksIcon,
  ListDashesIcon,
  ListIcon,
  ListNumbersIcon,
  ListPlusIcon,
  LockIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MegaphoneIcon,
  MenuIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSquareIcon,
  MonitorIcon,
  NotePencilIcon,
  NotificationIcon,
  OpenIcon,
  PaperclipIcon,
  PenNibIcon,
  PhoneIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSquareIcon,
  PresentationIcon,
  PrinterIcon,
  QuestionIcon,
  QuestionMarkIcon,
  ScalesIcon,
  ScrollIcon,
  SelectionIcon,
  ShareNetworkIcon,
  ShieldWarningIcon,
  ShoppingCartIcon,
  SignOutIcon,
  SlidersIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparkleIcon,
  StarIcon,
  SwapIcon,
  TagIcon,
  TargetIcon,
  TextAaIcon,
  TextAlignCenterIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextBIcon,
  TextIndentIcon,
  TextItalicIcon,
  TextOutdentIcon,
  TextStrikethroughIcon,
  TextUnderlineIcon,
  TimerIcon,
  TrashIcon,
  UploadIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  UsersThreeIcon,
  VideoIcon,
  WalletIcon,
  WarningCircleIcon,
  WarningIcon,
  XCircleIcon,
  XIcon,
} from '@/assets/icons/regular'
import {
  FacebookLogoIcon,
  InstagramLogoIcon,
  LinkedinLogoIcon,
  YoutubeLogoIcon,
} from '@/assets/icons/social'

function createIconComponent(icon: any, size: number) {
  return defineComponent({
    setup(_, { attrs }) {
      return () => h(icon, { ...attrs, size })
    },
  })
}

const Icon16pxCaretDown = createIconComponent(CaretDownFilledIcon, 16)

const aliases: Partial<IconAliases> = {
  arrowBendUpLeft: ArrowBendUpLeftIcon,
  arrowBendUpRight: ArrowBendUpRightIcon,
  arrowCircleLeft: ArrowCircleLeftIcon,
  arrowCircleRight: ArrowCircleRightIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowsClockwise: ArrowsClockwiseIcon,
  arrowsOutCardinal: ArrowsOutCardinalIcon,
  arrowSquareOut: ArrowSquareOut,
  arrowSquareRight: ArrowSquareRight,
  arrowUp: ArrowUpIcon,
  arrowUpRight: ArrowUpRight,
  bookBookmark: BookBookmarkIcon,
  bookmark: BookmarkIcon,
  bookOpenText: BookOpenTextIcon,
  books: BooksIcon,
  briefcase: BriefcaseIcon,
  calendarBlank: CalendarBlankIcon,
  calendarCheck: CalendarCheckIcon,
  camera: CameraIcon,
  caretCircleLeft: CaretCircleLeftIcon,
  caretCircleRight: CaretCircleRightIcon,
  caretCircleUp: CaretCircleUpIcon,
  caretDoubleLeft: CaretDoubleLeftIcon,
  caretDoubleRight: CaretDoubleRightIcon,
  caretDown: CaretDownIcon,
  caretLeft: CaretLeftIcon,
  caretRight: CaretRightIcon,
  caretUp: CaretUpIcon,
  chatCircleDots: ChatCircleDotsIcon,
  chat: ChatIcon,
  chats: ChatsIcon,
  chatTeardrop: ChatTeardropIcon,
  chatText: ChatTextIcon,
  checkCircle: CheckCircleIcon,
  check: CheckIcon,
  checkSuccess: CheckSuccessIcon,
  circle: CircleIcon,
  clipboard: ClipboardIcon,
  clock: ClockIcon,
  copy: CopyIcon,
  creditCard: CreditCardIcon,
  crop: CropIcon,
  database: DatabaseIcon,
  deviceMobileCamera: DeviceMobileCameraIcon,
  deviceTablet: DeviceTabletIcon,
  dotsThree: DotsThreeIcon,
  download: DownloadIcon,
  downloadSimple: DownloadSimpleIcon,
  envelope: EnvelopeIcon,
  eta: EtaIcon,
  eyeClosed: EyeClosedIcon,
  eye: EyeIcon,
  eyeSlash: EyeSlashIcon,
  fileArrowDown: FileArrowDownIcon,
  fileArrowUp: FileArrowUpIcon,
  fileCode: FileCodeIcon,
  fileCsv: FileCsvIcon,
  fileDoc: FileDocIcon,
  fileMagnifyingGlass: FileMagnifyingGlassIcon,
  filePdf: FilePdfIcon,
  filePlus: FilePlusIcon,
  fileText: FileTextIcon,
  flag: FlagIcon,
  folderArrowDown: FolderArrowDownIcon,
  folderArrowUp: FolderArrowUpIcon,
  folder: FolderIcon,
  folderLock: FolderLockIcon,
  folderMinus: FolderMinusIcon,
  folderOpen: FolderOpenIcon,
  folderPlus: FolderPlusIcon,
  funnel: FunnelIcon,
  funnelSimple: FunnelSimpleIcon,
  funnelSimpleX: FunnelSimpleXIcon,
  funnelX: FunnelXIcon,
  gear: GearIcon,
  globe: GlobeIcon,
  hand: HandIcon,
  handPointing: HandPointingIcon,
  handsClapping: HandsClappingIcon,
  handShake: HandShakeIcon,
  handWaving: HandWavingIcon,
  headphones: HeadphonesIcon,
  heart: HeartIcon,
  house: HouseIcon,
  houseLine: HouseLineIcon,
  identificationCard: IdentificationCardIcon,
  key: KeyIcon,
  lightbulb: LightbulbIcon,
  link: LinkIcon,
  listBullets: ListBulletsIcon,
  listChecks: ListChecksIcon,
  listDashes: ListDashesIcon,
  list: ListIcon,
  listNumbers: ListNumbersIcon,
  listPlus: ListPlusIcon,
  lock: LockIcon,
  lockOpen: LockOpenIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  mapPin: MapPinIcon,
  mapTrifold: MapTrifoldIcon,
  megaphone: MegaphoneIcon,
  microphone: MicrophoneIcon,
  minusCircle: MinusCircleIcon,
  minusSquare: MinusSquareIcon,
  monitor: MonitorIcon,
  notePencil: NotePencilIcon,
  notification: NotificationIcon,
  open: OpenIcon,
  paperclip: PaperclipIcon,
  penNib: PenNibIcon,
  phone: PhoneIcon,
  plusCircle: PlusCircleIcon,
  plusSquare: PlusSquareIcon,
  presentation: PresentationIcon,
  printer: PrinterIcon,
  question: QuestionIcon,
  questionMark: QuestionMarkIcon,
  scales: ScalesIcon,
  selection: SelectionIcon,
  shareNetwork: ShareNetworkIcon,
  shieldWarning: ShieldWarningIcon,
  shoppingCart: ShoppingCartIcon,
  signOut: SignOutIcon,
  sliders: SlidersIcon,
  sortAscending: SortAscendingIcon,
  sortDescending: SortDescendingIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  swap: SwapIcon,
  tag: TagIcon,
  target: TargetIcon,
  textAa: TextAaIcon,
  textAlignCenter: TextAlignCenterIcon,
  textAlignLeft: TextAlignLeftIcon,
  textAlignRight: TextAlignRightIcon,
  textB: TextBIcon,
  textIndent: TextIndentIcon,
  textItalic: TextItalicIcon,
  textOutdent: TextOutdentIcon,
  textStrikethrough: TextStrikethroughIcon,
  textUnderline: TextUnderlineIcon,
  timer: TimerIcon,
  trash: TrashIcon,
  userCircle: UserCircleIcon,
  user: UserIcon,
  users: UsersIcon,
  usersThree: UsersThreeIcon,
  video: VideoIcon,
  wallet: WalletIcon,
  warningCircle: WarningCircleIcon,
  xCircle: XCircleIcon,
  x: XIcon,
  arrowCircleLeftBold: ArrowCircleLeftBoldIcon,
  arrowCircleRightBold: ArrowCircleRightBoldIcon,
  arrowLeftBold: ArrowLeftBoldIcon,
  arrowRightBold: ArrowRightBoldIcon,
  arrowSquareOutBold: ArrowSquareOutBoldIcon,
  arrowUpRightBold: ArrowUpRightBoldIcon,
  caretCircleDownBold: CaretCircleDownBoldIcon,
  caretCircleLeftBold: CaretCircleLeftBoldIcon,
  caretCircleRightBold: CaretCircleRightBoldIcon,
  caretCircleUpBold: CaretCircleUpBoldIcon,
  caretDoubleDownBold: CaretDoubleDownBoldIcon,
  caretDoubleLeftBold: CaretDoubleLeftBoldIcon,
  caretDoubleRightBold: CaretDoubleRightBoldIcon,
  caretDoubleUpBold: CaretDoubleUpBoldIcon,
  caretDownBold: CaretDownBoldIcon,
  caretLeftBold: CaretLeftBoldIcon,
  caretRightBold: CaretRightBoldIcon,
  caretUpBold: CaretUpBoldIcon,
  chatCircleBold: ChatCircleBoldIcon,
  checkBold: CheckBoldIcon,
  linkBold: LinkBoldIcon,
  minusBold: MinusBoldIcon,
  minusSquareBold: MinusSquareBoldIcon,
  pencilSimpleLineBold: PencilSimpleLineBoldIcon,
  plusBold: PlusBoldIcon,
  plusSquareBold: PlusSquareBoldIcon,
  spinnerGapBold: SpinnerGapBoldIcon,
  userBold: UserBoldIcon,
  warningBold: WarningBoldIcon,
  warningCircleBold: WarningCircleBoldIcon,
  warningDiamondBold: WarningDiamondBoldIcon,
  xBold: XBoldIcon,
  bookmarkFilled: BookmarkFilledIcon,
  calendarDotsFilled: CalendarDotsFilledIcon,
  caretDownFilled: CaretDownFilledIcon,
  caretLeftFilled: CaretLeftFilledIcon,
  caretRightFilled: CaretRightFilledIcon,
  caretUpFilled: CaretUpFilledIcon,
  chatCircleFilled: ChatCircleFilledIcon,
  chatTeardropFilled: ChatTeardropFilledIcon,
  checkCircleFilled: CheckCircleFilledIcon,
  databaseFilled: DatabaseFilledIcon,
  dotActive: DotActive,
  dotInactive: DotInactive,
  envelopeFilled: EnvelopeFilledIcon,
  houseFilled: HouseFilledIcon,
  infoFilled: InfoFilledIcon,
  magnifyingGlassFilled: MagnifyingGlassFilledIcon,
  mapPinFilled: MapPinFilledIcon,
  pencilLineFilled: PencilLineFilledIcon,
  playFilled: PlayFilledIcon,
  questionFilled: QuestionFilledIcon,
  starFilled: StarFilledIcon,
  trashFilled: TrashFilledIcon,
  userCircleFilled: UserCircleFilledIcon,
  warningCircleFilled: WarningCircleFilledIcon,
  warningDiamondFilled: WarningDiamondFilledIcon,
  warningFilled: WarningFilledIcon,
  xCircleFilled: XCircleFilledIcon,
  facebookLogo: FacebookLogoIcon,
  instagramLogo: InstagramLogoIcon,
  linkedinLogo: LinkedinLogoIcon,
  youtubeLogo: YoutubeLogoIcon,
  briefcaseLight: BriefcaseLightIcon,
  coinsLight: CoinsLightIcon,
  handCoinsLight: HandCoinsLightIcon,
  heartbeatLight: HeartbeatLightIcon,
  moneyLight: MoneyLightIcon,
  closeIcon: CloseIcon,
  fileIcon: FileIcon,
  infoRegular: InfoIcon,
  menuIcon: MenuIcon,
  warningRegular: WarningIcon,
  calendar: CalendarBlankIcon,
  checkboxIndeterminate: CheckboxOffIcon,
  checkboxOff: CheckboxOffIcon,
  checkboxOn: CheckboxOnIcon,
  clear: XCircleFilledIcon,
  delete: TrashIcon,
  delimiter: undefined,
  dropdown: Icon16pxCaretDown,
  edit: undefined,
  error: WarningDiamondFilledIcon,
  expand: CaretDownIcon,
  file: PaperclipIcon,
  first: undefined,
  info: InfoFilledIcon,
  last: undefined,
  loading: undefined,
  minus: MinusIcon,
  next: CaretRightIcon,
  plus: PlusIcon,
  prev: CaretLeftIcon,
  radioOff: RadioOffIcon,
  radioOn: RadioOnIcon,
  ratingEmpty: undefined,
  ratingFull: undefined,
  ratingHalf: undefined,
  sortAsc: undefined,
  sortDesc: undefined,
  subgroup: QuestionIcon,
  success: CheckCircleFilledIcon,
  unfold: undefined,
  warning: WarningFilledIcon,
  collapse: CaretUpIcon,
  complete: CheckIcon,
  cancel: undefined,
  close: XIcon,
  closeFilled: XCircleFilledIcon,
  back: CaretLeftIcon,
  search: MagnifyingGlassIcon,
  checkPrimary: CheckIcon,
  upload: UploadIcon,
  tooltip: QuestionIcon,
  scroll: ScrollIcon,
  circleFilled: CircleFilledIcon,
  spinner: SpinnerGapBoldIcon,
}

const rcIcons: IconSet = {
  component: (props: IconProps) => {
    switch (props.icon) {
      case 'rc-caret-left':
        return h(CaretLeftIcon, props)

      case 'rc-success':
        return h(CheckSuccessIcon, props)

      case 'rc-caret-down-filled':
        return h(CaretDownFilledIcon, props)

      case 'rc-caret-double-right-bold':
        return h(CaretDoubleRightBoldIcon, props)

      case 'rc-caret-double-left-bold':
        return h(CaretDoubleLeftBoldIcon, props)

      case 'rc-caret-right-bold':
        return h(CaretRightBoldIcon, props)

      case 'rc-caret-left-bold':
        return h(CaretLeftBoldIcon, props)

      // Add other cases here
      default:
        return h('span') // Fallback if the icon is not found
    }
  },
}

export { aliases, rcIcons }
